// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYYO1RnYI8Jp5TrwcFX5EWw6z0zjWOEZQ',
    appId: '1:718580602849:web:b8b4cca1bb5aa04ed8e4a0',
    messagingSenderId: '718580602849',
    projectId: 'buggy-backend-5194d',
    authDomain: 'buggy-backend-5194d.firebaseapp.com',
    storageBucket: 'buggy-backend-5194d.firebasestorage.app',
    measurementId: 'G-YM34Y913ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJhaiNyIWG6vlvPQvlphmoMmmPvLtaM7Y',
    appId: '1:718580602849:android:2f44ee059b31fe5ed8e4a0',
    messagingSenderId: '718580602849',
    projectId: 'buggy-backend-5194d',
    storageBucket: 'buggy-backend-5194d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDs_UVkGq9qT0eVCtYz70Hcnq-D6MWghw',
    appId: '1:718580602849:ios:9f32e91e6b66f4bed8e4a0',
    messagingSenderId: '718580602849',
    projectId: 'buggy-backend-5194d',
    storageBucket: 'buggy-backend-5194d.firebasestorage.app',
    iosBundleId: 'com.example.buggyMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDs_UVkGq9qT0eVCtYz70Hcnq-D6MWghw',
    appId: '1:718580602849:ios:9f32e91e6b66f4bed8e4a0',
    messagingSenderId: '718580602849',
    projectId: 'buggy-backend-5194d',
    storageBucket: 'buggy-backend-5194d.firebasestorage.app',
    iosBundleId: 'com.example.buggyMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYYO1RnYI8Jp5TrwcFX5EWw6z0zjWOEZQ',
    appId: '1:718580602849:web:62e44420a6105ba9d8e4a0',
    messagingSenderId: '718580602849',
    projectId: 'buggy-backend-5194d',
    authDomain: 'buggy-backend-5194d.firebaseapp.com',
    storageBucket: 'buggy-backend-5194d.firebasestorage.app',
    measurementId: 'G-PX25T9EEMZ',
  );
}
